# Generated by Django 3.1.7 on 2022-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220116_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='the title', max_length=200),
        ),
    ]
